{
 "title": "Github",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "owner",
    "label": "Owner",
    "query": {
     "query": "label_values(github_repo_info,owner)"
    }
   },
   { "name": "forks", "label": "Include forks", "query": "yes : 1,no : 0" },
   {
    "name": "repositories",
    "label": "Repositories",
    "query": {
     "query": "query_result(github_repo_is_fork{owner=\"$owner\"} <= $forks)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Open issues/PRs",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(github_repo_issues_total{owner=\"$owner\",status=\"open\"} + github_repo_pull_request_total{owner=\"$owner\",status=\"open\"},\"repo\",\"$1\",\"repository\",\"$owner/(.+)\") > 0 and on(owner,repository) github_repo_is_fork{repository=~\"$repositories\"} <= $forks",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top referrers (unique visitors)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (referrer) (github_repo_traffic_referring_sites_unique_vistors{owner=\"$owner\"} and on(owner,repository) github_repo_is_fork{repository=~\"$repositories\"} <= $forks)",
     "legendFormat": "{{referrer}}"
    }
   ]
  },
  {
   "title": "Languages (Size)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (language) (github_repo_languages_size{owner=\"$owner\"} and on(owner,repository) github_repo_is_fork{repository=~\"$repositories\"} <= $forks)",
     "legendFormat": "{{language}}"
    }
   ]
  },
  {
   "title": "Github API limit used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - github_rate_limit_remaining / github_rate_limit_limit",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Stars",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(github_repo_stars_total{owner=\"$owner\"},\"repo\",\"$1\",\"repository\",\"$owner/(.{0,28}).*\") and on(owner,repository) github_repo_is_fork{repository=~\"$repositories\"} <= $forks",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Watchers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(github_repo_watchers_total{owner=\"$owner\"},\"repo\",\"$1\",\"repository\",\"$owner/(.{0,28}).*\") and on(owner,repository) github_repo_is_fork{repository=~\"$repositories\"} <= $forks",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(github_repo_fork_total{owner=\"$owner\"},\"repo\",\"$1\",\"repository\",\"$owner/(.{0,28}).*\") and on(owner,repository) github_repo_is_fork{repository=~\"$repositories\"} <= $forks",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Views",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(increase(last_over_time(github_repo_traffic_views{owner=\"$owner\",week=\"latest\"}[1h:1h])[1h:]),\"repo\",\"$1\",\"repository\",\"$owner/(.+)\") and on(owner,repository) github_repo_is_fork{repository=~\"$repositories\"} <= $forks",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Unique visitors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(increase(last_over_time(github_repo_traffic_unique_vistors{owner=\"$owner\",week=\"latest\"}[1h:1h])[1h:]),\"repo\",\"$1\",\"repository\",\"$owner/(.+)\") and on(owner,repository) github_repo_is_fork{repository=~\"$repositories\"} <= $forks",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Clones",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(increase(last_over_time(github_repo_traffic_clones{owner=\"$owner\",week=\"latest\"}[1h:1h])[1h:]),\"repo\",\"$1\",\"repository\",\"$owner/(.+)\") and on(owner,repository) github_repo_is_fork{repository=~\"$repositories\"} <= $forks",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Unique cloners",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(increase(last_over_time(github_repo_traffic_unique_clones{owner=\"$owner\",week=\"latest\"}[1h:1h])[1h:]),\"repo\",\"$1\",\"repository\",\"$owner/(.+)\") and on(owner,repository) github_repo_is_fork{repository=~\"$repositories\"} <= $forks",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Referrers (views)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(github_repo_traffic_referring_sites_views{owner=\"$owner\"},\"repo\",\"$1\",\"repository\",\"$owner/(.+)\") and on(owner,repository) github_repo_is_fork{repository=~\"$repositories\"} <= $forks",
     "legendFormat": "{{referrer}} ({{repo}})"
    }
   ]
  },
  {
   "title": "Referrers (unique visitors)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(github_repo_traffic_referring_sites_unique_vistors{owner=\"$owner\"},\"repo\",\"$1\",\"repository\",\"$owner/(.+)\") and on(owner,repository) github_repo_is_fork{repository=~\"$repositories\"} <= $forks",
     "legendFormat": "{{referrer}} ({{repo}})"
    }
   ]
  },
  {
   "title": "Popular content (views)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(github_repo_traffic_popular_content_views{owner=\"$owner\"},\"short_path\",\"$1\",\"path\",\"/$owner(/.{0,50}).*\") and on(owner,repository) github_repo_is_fork{repository=~\"$repositories\"} <= $forks",
     "legendFormat": "{{short_path}}"
    }
   ]
  },
  {
   "title": "Popular content (unique visitors)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(github_repo_traffic_popular_content_unique_vistors{owner=\"$owner\"},\"short_path\",\"$1\",\"path\",\"/$owner(/.{0,50}).*\") and on(owner,repository) github_repo_is_fork{repository=~\"$repositories\"} <= $forks",
     "legendFormat": "{{short_path}}"
    }
   ]
  }
 ]
}