{
 "title": "Netatmo",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netatmo_sensor_temperature_celsius{module=\"Outdoor Module\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netatmo_sensor_temperature_celsius{module=\"Weather Station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netatmo_sensor_pressure_mb{module=\"Weather Station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Noise",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netatmo_sensor_noise_db{module=\"Weather Station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outdoor",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "netatmo_sensor_temperature_celsius{module=\"Outdoor Module\"}",
     "legendFormat": "Outdoor"
    }
   ]
  },
  {
   "title": "Indoor",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "label_replace(netatmo_sensor_temperature_celsius{module!=\"Outdoor Module\"},\"module\",\"Living room\",\"module\",\"Weather Station\")",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Signal strength",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "-netatmo_sensor_wifi_signal_strength",
     "legendFormat": "WIFI"
    },
    {
     "expr": "-label_replace(netatmo_sensor_rf_signal_strength,\"module\",\"Outdoor\",\"module\",\"Outdoor Module\")",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(netatmo_sensor_humidity_percent,\"module\",\"Living room\",\"module\",\"Weather Station\"),\"module\",\"Outdoor\",\"module\",\"Outdoor Module\")",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "CO2 ppm",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(netatmo_sensor_co2_ppm{module!=\"Outdoor Module\"},\"module\",\"Living room\",\"module\",\"Weather Station\")",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(netatmo_sensor_battery_percent,\"module\",\"Outdoor\",\"module\",\"Outdoor Module\")",
     "legendFormat": "{{module}}"
    }
   ]
  }
 ]
}